// Generated by CoffeeScript 1.3.3
(function() {

  window.Audio = (function() {

    function Audio(target) {
      if ($.browser.webkit || $.browser.msie) {
        this.element = document.getElementById(target + 'mp3');
      } else {
        this.element = document.getElementById(target + 'ogg');
      }
    }

    Audio.prototype.play = function() {
      return this.element.play();
    };

    Audio.prototype.pause = function() {
      return this.element.pause();
    };

    return Audio;

  })();

}).call(this);
